### ISSUE TITLE
Not in packagist

### ISSUE THREAD

**Issue by superdav42** [mageplaza/magento-2-thai-language-pack#1]
```
composer require mageplaza/magento-2-thai-language-pack:dev-master
```
fails with 
 [InvalidArgumentException]                                                   
  Could not find a matching version of package mageplaza/magento-2-thai-langu  
  age-pack. Check the package spelling, your version constraint and that the   
  package is available in a stability which matches your minimum-stability (s  
  table).     
doens't appear to be in packgist.org

**Comment by imsamthomas** [comment]
Hi,

Please try again, we have [added](https://packagist.org/packages/mageplaza/magento-2-thai-language-pack).

You should contribute the Thai language pack at https://crowdin.com/project/magento-2/th 
It is 0% translated now.
